const a =prompt("sizninig ismingiz nima");
const b =prompt("sizninig familyangiz nima");
const c =prompt("siz necha yoshtasiz");
const d =prompt("siz qayerda yashaysiz");
const e =prompt("sizninig yoqtirgan faning giz");
 console.log(a);
 console.log(b);
 console.log(c);
 console.log(d);
 console.log(e);